//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Result = new HashSet<Result>();
        }
    
        public int AnimalId { get; set; }
        public string Animal_FullName { get; set; }
        public string Animal_Number { get; set; }
        public Nullable<int> Animal_PersonId { get; set; }
        public int Animal_TestId { get; set; }
        public int Animal_AnimalTypeId { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual TestType TestType { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Result { get; set; }
    }
}
